export const RESET_RESULT = 'RESET_RESULT';
export const GET_RESULT = 'GET_RESULT';
export const ADD_RESULT_TO_LIST = 'ADD_RESULT_TO_LIST';
export const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM';

export const OPEN_ALERT_MODAL = 'OPEN_ALERT_MODAL';
export const CLOSE_ALERT_MODAL = 'CLOSE_ALERT_MODAL';

export const TOGGLE_MENU = 'TOGGLE_MENU';

export const SET_MAP_INSTANCE = 'SET_MAP_INSTANCE';
